server:
  port: 8989
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: users_route
          uri: http://localhost:9999/
          predicates:
            - Path=/user/**
        - id: product_route
          uri: http://localhost:9998/
          predicates:
            - Path=/product/**
management:
  endpoints:
    web:
      exposure:
        include: "*"   #\u5F00\u542F\u6240\u6709web\u7AEF\u70B9\u66B4\u9732